pipeline {
    agent any
    tools {
        maven 'Maven 3.9.4'
        jdk 'Java17'
    }
    stages {
        stage ('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
    }
}